name: unfreeze
description: A Dart package for isolate execution of asynchronous tasks using Dart isolates.
version: 1.0.0
repository: https://github.com/arrahmanbd/unfreeze
homepage: https://github.com/arrahmanbd/unfreeze

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
